/* eslint-disable */
import '~/air-datepicker/dist/js/datepicker.min';
import '~/air-datepicker/dist/css/datepicker.min.css';
import '~/inputmask/dist/jquery.inputmask.min';
import '~/ion-rangeslider/js/ion.rangeSlider';
import '~/ion-rangeslider/css/ion.rangeSlider.css';
// import '~/masonry-layout/dist/masonry.pkgd.min';
import 'swiper/swiper-bundle.css';
import './main.scss';
import './js';
import './js/plugins/jquery.simplePagination.js';
import './js/mask';
import './blocks/date-dropdown/date-dropdown';
import './blocks/datepicker/datepicker';
import './blocks/filter-date/filter-date';
import './blocks/expand-list/expand-list';
import './blocks/like-button/like-button';
import './blocks/rate-buttons/rate-buttons';
import './blocks/range-slider/range-slider';
import './blocks/pagination/pagination';
import './blocks/card-room/card-room';
import './blocks/cards-page/cards-page';
// import './js/plugins/iqdropdown' ;
// import './js/plugins/date-picker';

// import './js/mask';
// import './js/checkbox';
// import './js/like-dislike';
// import './js/rate';
// import './js/range-slider';
// import './js/pagination';
// import './js/mansory';
// import './js/swiper';
// import './js/gamburger';
// import './js/section-main';
